package monorail;


import monorail.PassengerMethodsUI;
import java.util.ArrayList;
import monorail.Passenger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Passenger_specific extends javax.swing.JFrame {
        PassengerMethodsUI PMUI = new PassengerMethodsUI();
        ArrayList<Passenger> passengers = Monorail.passengers;
        Passenger passenger = passengers.get(0);
    /**
     * Creates new form Passenger
     */
    public Passenger_specific() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Createaccount_RB = new javax.swing.JRadioButton();
        Updateaccount_RB = new javax.swing.JRadioButton();
        Deleteaccount_RB = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        Addbooking_RB = new javax.swing.JRadioButton();
        Managebooking_RB = new javax.swing.JRadioButton();
        Displaybooking_RB = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome Passenger choose from the following");

        Createaccount_RB.setText("Create Account");

        Updateaccount_RB.setText("Update Account");

        Deleteaccount_RB.setText("Delete Account");

        Addbooking_RB.setText("Add Booking");
        Addbooking_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addbooking_RBActionPerformed(evt);
            }
        });

        Managebooking_RB.setText("Manage Bookings");
        Managebooking_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Managebooking_RBActionPerformed(evt);
            }
        });

        Displaybooking_RB.setText("Display Booking");
        Displaybooking_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Displaybooking_RBActionPerformed(evt);
            }
        });

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Createaccount_RB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(Updateaccount_RB)
                                .addGap(51, 51, 51)
                                .addComponent(Deleteaccount_RB)
                                .addGap(55, 55, 55))
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(Addbooking_RB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Managebooking_RB)
                                .addGap(42, 42, 42)
                                .addComponent(Displaybooking_RB)
                                .addGap(44, 44, 44)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Createaccount_RB)
                    .addComponent(Updateaccount_RB)
                    .addComponent(Deleteaccount_RB))
                .addGap(35, 35, 35)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbooking_RB)
                    .addComponent(Managebooking_RB)
                    .addComponent(Displaybooking_RB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                            PMUI.setVisible(true);
if (Addbooking_RB.isSelected()) {
                    PMUI.addSeatsAndRoute();


            } else if(Managebooking_RB.isSelected()) {
                PMUI.manageBookings(passenger.getBookings());
            }
            else{
                PMUI.displayBookings(passenger.getBookings());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Managebooking_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Managebooking_RBActionPerformed

    }//GEN-LAST:event_Managebooking_RBActionPerformed

    private void Addbooking_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addbooking_RBActionPerformed


    }//GEN-LAST:event_Addbooking_RBActionPerformed

    private void Displaybooking_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Displaybooking_RBActionPerformed

    }//GEN-LAST:event_Displaybooking_RBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passenger_specific().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Addbooking_RB;
    private javax.swing.JRadioButton Createaccount_RB;
    private javax.swing.JRadioButton Deleteaccount_RB;
    private javax.swing.JRadioButton Displaybooking_RB;
    private javax.swing.JRadioButton Managebooking_RB;
    private javax.swing.JRadioButton Updateaccount_RB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
